// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxQ6amVJRRspmI47YNilPr6p2AO0LpiZI',
    appId: '1:256241990314:web:4a1887b6f47314f57f2ed3',
    messagingSenderId: '256241990314',
    projectId: 'open-sooq-2cecd',
    authDomain: 'open-sooq-2cecd.firebaseapp.com',
    storageBucket: 'open-sooq-2cecd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrw9b7pU0VO6LZmDxiIIvpEk3qm3_4xGI',
    appId: '1:256241990314:android:1c3c5358318599667f2ed3',
    messagingSenderId: '256241990314',
    projectId: 'open-sooq-2cecd',
    storageBucket: 'open-sooq-2cecd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA98ewLShNM3m3F4Tdlpngz9CH2UvmNDYo',
    appId: '1:256241990314:ios:127ba7375bb597847f2ed3',
    messagingSenderId: '256241990314',
    projectId: 'open-sooq-2cecd',
    storageBucket: 'open-sooq-2cecd.appspot.com',
    iosClientId: '256241990314-jb1adjskl03k9g3jsigkf75f9vfiuta5.apps.googleusercontent.com',
    iosBundleId: 'com.example.openSooq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA98ewLShNM3m3F4Tdlpngz9CH2UvmNDYo',
    appId: '1:256241990314:ios:127ba7375bb597847f2ed3',
    messagingSenderId: '256241990314',
    projectId: 'open-sooq-2cecd',
    storageBucket: 'open-sooq-2cecd.appspot.com',
    iosClientId: '256241990314-jb1adjskl03k9g3jsigkf75f9vfiuta5.apps.googleusercontent.com',
    iosBundleId: 'com.example.openSooq',
  );
}
